### ISSUE TITLE
flutter_driver from sdk is incompatible with fast_flutter_driver

### ISSUE THREAD

**Issue by Lootwig** [tomaszpolanski/fast_flutter_driver#118]
Running with SDK version 2.10.0 as well as 2.12.0, I get this error when keeping `flutter_driver: sdk: flutter` in my pubspec. the conflict ist on the args package, flutter_driver seems to depend on 1.6.0 even with the 2.12.0 SDK version. I haven't found any open or closed issues on this, which SDK version is everyone else using?

**Comment by tomaszpolanski** [comment]
Hey @Lootwig 
by SDK you mean Dart version, right?
Could also you say what Flutter and `flutter_driver` version you are using?

I've migrated `flutter_driver` to a version that supports Dart 2.12+ and `args` 2.0.0. Could you try using the latest versions?

**Comment by Lootwig** [comment]
yes the version number refers to the dart SDK. My flutter version is 2.0.4.
I've checked the pubspec.lock for flutter_driver, and for some reason it says "0.0.0" for the version. There might be an error here.

The problem is not the lack of support for args 2.0.0 - but that args was pinned to 1.6.0 by the flutter_driver dependency.

I'll check if there's something fishy with those packages and report back.

**Comment by Lootwig** [comment]
Okay so I've just created a blank flutter project.

<details>
  <summary>flutter doctor</summary>
  
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19042.867], locale
    en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.3)
[√] Android Studio (version 4.0)
[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
[√] VS Code (version 1.55.1)
[√] Connected device (3 available)

• No issues found!
```
</details>

<details>
<summary>pubspec.yaml</summary>

```yaml
name: fastdriver_dep_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  fast_flutter_driver: ^3.0.0+1

flutter:
  uses-material-design: true
```
</details>

Neither this nor fast_flutter_driver: ^2.0.0 can be resolved due to the "args" incompatibility.
